// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller

// import { application } from "./application"

// import HelloController from "./hello_controller"
// application.register("hello", HelloController)


import { Application } from "stimulus"
import { definitionsFromContext } from "stimulus/webpack-helpers"

const application = Application.start()
const context = require.context("controllers", true, /_controller\.js$/)
application.load(definitionsFromContext(context))
